name: "Deploy"
env:
  SPHINX_API_KEY: ${{ secrets.SPHINX_API_KEY }}
  ONFINALITY_API_KEY: ${{ secrets.ONFINALITY_API_KEY }}
  ADMIN: "0x423420Ae467df6e90291fd0252c0A8a637C1e03f"
  PAUSERS: "0x423420Ae467df6e90291fd0252c0A8a637C1e03f"
  AXELAR_GATEWAY: "0xe432150cce91c13a887f7D836923d5597adD8E31"

on:
  push:
    tags:
      - "release-*"

jobs:
  sphinx-propose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install Sphinx Solidity Library
        run: yarn sphinx install
      - name: Propose Sphinx Deployment
        run: npx sphinx propose script/Axelar.s.sol --networks mainnets
